#!/bin/sh

FILE="/etc/resolv.conf"
STRING="192.168.100.10"

LINE_COUNT=$(wc -l < "$FILE")

if [ "$LINE_COUNT" -eq 1 ]; then
	echo "nameserver 192.168.100.10" >> "$FILE"
    exit 0
else

	if ! grep -q "$STRING" "$FILE"; then
    		sed -i '2i nameserver 192.168.100.10' "$FILE"
	fi
fi

exit 0
